### ISSUE TITLE
Difficulté intégration graphique dash dans execution Flask

### ISSUE THREAD

**Issue by NicolasBRUNEAU** [pierrepo/volcano#1]
Je rencontre quelques difficultés afin d'intégrer du code 'Dash' dans du code 'Flask'.
Je m'explique, j'aimerais utiliser prioritairement le serveur Flask, car il permet de gérer l'intégralité du code html (head, meta, link, body...) ET permet d'utiliser un moteur de templates (jinja 2) afin de séparer l'exécution de l'affichage avec l'execution 'serveur'. 
Dash, qui utilise lui aussi un serveur flask en aval, ne peut lui, gérer que la partie 'body' du HTML. De plus il ne possède pas de moteur de templates.
De plus, dash ne permet pas d'utiliser de fichier 'local' en ce qui concerne les JS et CSS : ils doivent provenir un hébergeur pour pouvoir être utilisé.

Dans un souci de confort de programmation et de clarté du code (html séparé du python), j'aurai aimé savoir si il existe un moyen, pour récupérer uniquement la sortie Dash pour les graphiques, afin de l'utiliser dans la routine du serveur Flask, ou alors si on peut 'switch' d'application (flask -> dash) pour une partie de la page HTML (particulièrement pour la partie du graph dynamique)?

Si cela est possible, auriez-vous de la documentation à ce sujet ?

En vous remerciant,

BRUNEAU Nicolas

**Comment by pierrepo** [comment]
Bonjour @NicolasBRUNEAU 

ta question est très intéressante. Par défaut Dash devient lui-même une application Flask.

Il est a priori possible de mélanger l'application Flask et l'application Dash pour conserver les fonctionnalités natives de Flask : [Running a Dash app within a Flask app](https://stackoverflow.com/questions/45845872/running-a-dash-app-within-a-flask-app). Voir aussi [Deploying Dash Apps](https://plot.ly/dash/deployment)

Pour ce qui est de servir les fichiers css en local, il y a une astuce ici [How do I use Dash to add local css?](https://community.plot.ly/t/how-do-i-use-dash-to-add-local-css/4914).

Je te rappelle qu'on trouve sur le site GitHub de Plotly des démos (avec les codes sources) de Dash. Par exemple : 

- New York Oil and Gas : [app](https://plot.ly/dash/gallery/new-york-oil-and-gas) et [code source](https://github.com/plotly/dash-oil-and-gas-demo)
- Goldman Sachs Report : [app](https://plot.ly/dash/gallery/goldman-sachs-report) et [code source](https://github.com/plotly/dash-goldman-sachs-report-demo)

---

Cela dit, si Dash te semble trop compliqué à prendre à main, tu peux aussi jeter un oeil à Bokeh, qui est une autre bibliothèque de visualisation interactive, qui fonctionne également avec Flask (mais plus simplement semblerait-il). Voici un exemple tiré de la [gallerie de Bokeh](https://bokeh.pydata.org/en/latest/docs/gallery.html) et basé sur [les films de la base IMDB](https://demo.bokehplots.com/apps/movies). Et pour finir deux tutoriels : 

- [Creating Interactive Bokeh Applications with Flask](http://biobits.org/bokeh-flask.html)
- [Responsive Bar Charts with Bokeh, Flask and Python 3](https://www.fullstackpython.com/blog/responsive-bar-charts-bokeh-flask-python-3.html)

---

Enfin, essaie de ne pas passer  trop de temps sur cette partie visualisation. L'objectif étant d'afficher les protéines sur le volcano plot, avec différentes couleurs suivant les zones où les protéines se trouvent. 

Si le graphique n'est pas interactif -- c'est-à-dire qu'il ne se rafraîchit pas automatiquement quand on modifie les valeurs de p-value ou log fold change -- ce n'est pas très grave. Il suffira d'avoir à côté un bouton "rafraîchir" qui régénérera le graphique (et la liste des protéines sélectionnées).

**Comment by pierrepo** [comment]
essaie aussi d'en discuter avec @fab-genty

**Comment by fab-genty** [comment]
Bonjour,

Serait il possible de vous rencontrer cette semaine pour parler du projet
volcano .De plus avez vous les données pour que je puisse  les tester sur
le code que j'ai réalisé

Cordialement

Fabien Genty

2017-10-22 18:12 GMT+02:00 Pierre Poulain <notifications@github.com>:
