### ISSUE TITLE
RDV + données

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/volcano#2]
> Serait il possible de vous rencontrer cette semaine pour parler du projet
volcano .De plus avez vous les données pour que je puisse  les tester sur
le code que j'ai réalisé
> Cordialement
> Fabien Genty

Bonjour @fab-genty Deux choses importantes : 

1. Pense à accepter l'invitation GitHub que j'ai envoyé pour ce dépôt GitHub (après notre première réunion).
2. Crée une nouvelle issue pour chaque sujet de discussion différent.

Concernant les données : j'ai mis un exemple de fichier dans le dossier data de ce dépôt. Plus de 4700 protéines identifiées et quantifiées par spectrométrie de masse. L'organisme étudié est la drosophile. La condition "A" est le contrôle et l'expérience "D" est le test.

Concernant le rendez-vous, je suis disponible : 

- demain, mardi 24/10 à 17h
- jeudi 26/10 à 8h30
- lundi 30/10 à 17h
- mardi 31/10 à 17h

Je te laisse voir avec @NicolasBRUNEAU quel créneau vous convient le mieux.

**Comment by NicolasBRUNEAU** [comment]
je suis disponible pour tout les créneaux

**Comment by pierrepo** [comment]
OK, on dit 17h ce soir alors. @NicolasBRUNEAU tu peux prévenir @fab-genty ?

**Comment by NicolasBRUNEAU** [comment]
bien pris, je lui transmet

**Comment by fab-genty** [comment]
cela me convient aussi

**Comment by pierrepo** [comment]
OK merci. A ce soir. Je vous donne rendez-vous à l'entrée de l'IJM mais côté UFR de Physique cette fois ;-)

**Comment by pierrepo** [comment]
Bonjour, 

suite à notre réunion, j'ai ajouté de la documentation dans le fichier `README.md` concernant la conversion d'identifiants via UniProt. J'ai également écrit un exemple d'utilisation de l'API Uniprot dans le script `uniprot_map_identifiers.py`.

Je clôture cette issue.
